### ISSUE TITLE
Usage with a JavaScript project

### ISSUE THREAD

**Issue by unthinkadmin** [biosustain/potion-node#18]
I have used flask-potion to quickly build my backend APIs and I loved it!

I'm wondering how can I use potion-node as a Javascript client in my project (I use ReactJS for my UI). The class templatization of TypeScript is not available in JavaScript, so how would I implement a CustomCache?

**Comment by akankshashriv** [comment]
Sorry, folks - the above post is mine.
Just realized I had posted from my organisation deploy bot's account.

**Comment by lyschoening** [comment]
As cache, you'll just need to provide an object that has `get(key)`, `put(key, item)` and `remove(key)` functions. You also don't have to provide a `cache` argument. If you don't provide a `cache` argument, this cache implementation will be used: https://github.com/biosustain/potion-node/blob/master/src/utils.ts#L105:L123
