### ISSUE TITLE
Race condition leading to unpopulated items returned by promise 

### ISSUE THREAD

**Issue by lyschoening** [biosustain/potion-node#29]
We have a query (that we run repetitively) that resolves an array of items each of which also has recursively resolving parents. We encountered a race conditions where sometimes some of the items in the array have parents that are not fully resolved. These parents have been constructed but the data for them has not been loaded. 

Looking at the code, it seems most likely that the race condition happens because:

1. Items are added to `PotionBase.cache` as soon as the constructor is initialized
2. The resolution of children uses `PotionBase.fetch()`
3. `PotionBase.fetch()` returns items from the cache, regardless of whether their promise has been resolved or not.

Assuming that circular references don't happen, the problem could be solved by placing a promise for the item (rather than the item itself) onto the cache.

**Comment by rolandjitsu** [comment]
@lyschoening a test case would be nice if possible. But if I understand correctly, is the issue at [core/potion.ts#L148](https://github.com/biosustain/potion-node/blob/master/src/core/potion.ts#L148)? We might be able to solve this by moving [core/potion.ts#L157](https://github.com/biosustain/potion-node/blob/master/src/core/potion.ts#L157) above the previous line, if there is truly a pending request for that resource.

**Comment by lyschoening** [comment]
@rolandjitsu I considered that as well. It might solve the specific issue we're experiencing, but it would still leave a race condition because there could be a pending request for a list of items.

**Comment by rolandjitsu** [comment]
Note that the fix for this is not yet published on NPM due to the issue with cross references.
