### ISSUE TITLE
potion is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by Alain1405** [biosustain/potion-node#7]
I'm trying to use `potion-node` with `"angular": "^1.5.6"`. 
When I try to inject it in a factory I get `potion is not using explicit annotation and cannot be invoked in strict mode`.

```
    .config(['potionProvider', 'API_URL', function (potionProvider, API_URL)
    {
        console.log('Configure potion provider');
        potionProvider.config(
            {
                prefix: '/api',
                host: API_URL
            }
        );
    }])
    .factory('crudClient', ['potion', function (potion){...}];);
```

Replacing, in node_modules/potion-client/angular.js
`this.$get = function ($cacheFactory, $q, $http) {`
with
`this.$get = ['$cacheFactory', '$q', '$http', function ($cacheFactory, $q, $http) {`
fixes the issue (or am I doing something wrong?).

**Comment by rolandjitsu** [comment]
@Alain1405 that is because you enabled strict DI. I'll make sure to use strict DI by default so these issues don't occur.

**Comment by Alain1405** [comment]
Thanks, that was super quick!
I'm planning to use potion-client with [angular-schema-form](https://github.com/json-schema-form/angular-schema-form).

**Comment by rolandjitsu** [comment]
@Alain1405 I will try to push a fix today. Meanwhile, you can disable [strict DI](https://docs.angularjs.org/api/ng/directive/ngApp) to make this work.
