### ISSUE TITLE
Error validating $ref on toMany relationship.

### ISSUE THREAD

**Issue by Alain1405** [biosustain/potion-node#8]
First of all, thanks for flask-potion, it is a great resource!
I've setup an API with potion-flask + flask-sqlalchemy. I can query and filter and all looks good. I would like to use the API on angularjs by I encounter an error when querying models with relationships.

The model `User` has a toMany relationship with `Controllers`:

```
class UserResource(ModelResource):
    class Meta:
        model = User
        exclude_fields = ['password_hash']
        include_type = True
        include_id = True

    class Schema:
        controllers = fields.ToMany('controllers')
```

My factory looks like:

```
require('core-js/shim');
require("reflect-metadata");
var Item = require("potion-client/angular").Item;
...
.module('myApp.common.factories', ['potion'])
.config(['potionProvider', function (potionProvider)
    {
        console.log('Configure potion provider');
        potionProvider.config(
            {
                prefix: '/api',
                host: http://localhost:8888
            }
        );
    }])
    .factory('crudClient', ['potion', function (potion){
        function init()
        {
            var User = Item; //Question below

            potion.register('/users', User);
            return User
        }
        return {
            init: init
        }
}];);
```

and in a controller, querying users like so: 

```
            var user = crudClient.init();
            user.query().then(function(users){
                 $scope.users = users;
            });
```

I get the following error:
`Uninterpretable or unknown resource URI: /controllers/:id:` when `parseUri` is called in base.js:

```
PotionBase.prototype.parseURI = function (uri) {
        uri = decodeURIComponent(uri);
        if (uri.indexOf(this.prefix) === 0) {
            uri = uri.substring(this.prefix.length);
        }
        for (var _i = 0, _a = Object.entries(this.resources); _i < _a.length; _i++) {
            var _b = _a[_i], resourceURI = _b[0], resource = _b[1];
            if (uri.indexOf(resourceURI + "/") === 0) {
                return { uri: uri, resource: resource, params: uri.substring(resourceURI.length + 1).split('/') };
            }
        }
        throw new Error("Uninterpretable or unknown resource URI: " + uri);
    };
```

Some debug info: 
In PotionBase.prototype.parseURI, uri is `"/api/controllers/id"`. This comes from a $ref in the schema, under the relationship field `controller`. uri makes `if (uri.indexOf(this.prefix) === 0)` evaluate `true`. uri is stripped to `/controllers/id` and it doesn't pass the condition `if (uri.indexOf(resourceURI + "/") === 0)` being resourceURI `"/users"`

Question 1:
Is this a bug or a misconfiguration?

Question 1: Is it correct to replace

```
class User extends Item
```

with

```
var User = Item; 
```

?

**Comment by rolandjitsu** [comment]
@Alain1405 thanks, but flask-potion is created and maintained by @lyschoening.

First of all, I suggest using the singular form for `/controllers`, as in `controller`, same for `/users`, should be `/user`.

Furthermore, you also need to register the other resource you have the relationship with. So if your `User` model contains a reference to some other resource, make sure to register it the same way you registered the `User`:

``` js
class Controller extends Item {}
potion.register('/controller', Controller);
```

The error message `Uninterpretable or unknown resource URI: /controllers/:id` tells exactly what I described above, that you haven't registered the resource.

Finally, for the ES5 version of extending a class, you should take a look at [es6-equivalents-in-es5](https://github.com/addyosmani/es6-equivalents-in-es5#classes), basically the proper way to do it is:

``` js
function User() {
    Item.call(this);
}

User.prototype = Object.create(Item.prototype);
```

If you followed all the steps correctly, it should be working.

**Comment by Alain1405** [comment]
Thanks fro the support @rolandjitsu 
As suggested by [the great link](https://github.com/addyosmani/es6-equivalents-in-es5#classes) you passed, I should register all members of Item explicitely as they are not part of `prototype`. In practice this mean that

```
function User() {
    Item.call(this);
}

User.prototype = Object.create(Item.prototype);
```

results in User instances not having `query`, `fetch`, `first` members.
`User2.query = Item.query;` would fix, but is this the expected behaviour?

**Comment by rolandjitsu** [comment]
@Alain1405 for static members you should use:

``` js
User.query = Item.query;
User.fetch = Item.fetch;
User.first = Item.first;
```

But this would get very repetitive when creating more resources, so you could create a mixin that creates a resource item for you:

``` js
var User = createResource('User');
potion.register('/user', User);

function createResource(name) {
    var Resource = new Function(
        'Item',
        'return function ' + name + '(properties) {Item.call(this, properties);}'
    )(Item);

    Resource.prototype = Object.create(Item.prototype);
    Resource.query = Item.query;
    Resource.fetch = Item.fetch;
    Resource.first = Item.first;

    return Resource;
}
```

Check this [fiddle](https://jsfiddle.net/rolandjitsu/kuu51xp2/) for a working example. Though, my best advise is to try to use ES6 syntax and use a transpiler.

**Comment by Alain1405** [comment]
Thanks again. I'll stick to ES5 for the time being!
